---

- hosts: localhost
  
  tasks:
    - name: Install specific version of openstacksdk
      pip:
        name: openstacksdk
        version: ">=1.0"  # 원하는 버전 조건 지정
      become: yes  # 필요에 따라 root 권한으로 실행

  tasks:
    - name: Lanuch an instance
      openstack.cloud.server:
        state: present
        name: "{{ instance_name }}"
        image: "{{ image_name }}"
        boot_from_volume: true
        volume_size: "{{ os_volume_size }}"
        terminate_volume: true
        flavor: "{{ flavor_name }}"
        network: "{{ network_name }}"
        security_groups: ["{{ security_group_name }}"]
        timeout: 200
        wait: yes
        userdata: |
          #cloud-config
          chpasswd:
            list: |
              root:password
              expire: false
      register: instance_info
